export const GET_PLAYER_INFO = 'GET_PLAYER_INFO';
export const GET_PLAYER_SCORE = 'GET_PLAYER_SCORE';
export const GET_GAME_TIMER = 'GET_GAME_TIMER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const STOP_TIMER = 'STOP_TIMER';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';
export const CHOOSE_DIFFICULTY = 'CHOOSE_DIFFICULTY';
export const CHOOSE_QUESTION_TYPE = 'CHOOSE_QUESTION_TYPE';
